### ISSUE TITLE
Web service to rebuild the index on the server

### ISSUE THREAD

**Issue by llgcode** [kawane/songbook#10]
Administrative service for rebuilding the index on the server

**Comment by jeancharles-roger** [comment]
It exists on `/admin/resetIndex`

**Comment by jeancharles-roger** [comment]
Maybe I should change it to ´/admin/index/reset'. What do you think ?

**Comment by jeancharles-roger** [comment]
It's now `/admin/index/reset`. The idea is `/admin/[section]/[command]`.

**Comment by llgcode** [comment]
ok

Laurent
<http://facebook.com/laurent.legoff.33>
<http://www.youtube.com/user/llgloul/videos>
<http://twitter.com/laurentlegoff>  <https://soundcloud.com/llgmusic>
