### ISSUE TITLE
Id URI 

### ISSUE THREAD

**Issue by llgcode** [kawane/songbook#11]
Songbook REST API may not change id when changing the name of the song. So it's preferable that's server manage id or URI. However if the user want to have an appropriate id/URI for his song he may want to suggest one, But changing it will not be a trivial change causing to break hyperlink. Change REST API implementation to reflect this spec.

**Comment by jeancharles-roger** [comment]
You're right Id shouldn't change (sorry my bad :) ). For the URI, a search URL may do the trick.

**Comment by llgcode** [comment]
done id is generated from artist+title and can't be changed
