### ISSUE TITLE
Proposal for song dsl

### ISSUE THREAD

**Issue by llgcode** [kawane/songbook#12]
Use a dsl for song so we can edit in a text editor.

#### Names:
 - chordlyric
 - lyriclang
 - lylang
 - lytext
 - chtxt
 - **songmark**

#### Extensions:
 - **.song**
 - .lyrics
 - .chl
 - .cl
 - .ly

#### Features:
 - simple edit lyrics and chords (using chord symbols)
 - identify simple rythmic measure (using |)
 - provide the tone of the song
 - differentiate verse from chorus and bridge by optinally labeling sections 
 - metadata support for indexing: title, artist, album, year
 - add extra information: links to audio, video or any page
 - tolerant: programs that interpret it may not failed at parsing it, in the worst case all is interpreted as lyrics. Metadata are optional

#### Syntax
My preference is to place chords above lyrics cause its more readable:
```
=== L'autre finistère (Les innocents)

album = Fous à lier
year = 1992
tone = G
video = http://www.youtube.com/watch?v=LkbzNlfYuiI

Verse:
 G 
Comprendrais tu ma belle qu'un jour fatigué
            F 
J'aille me briser la voix une dernière fois
        Em 
À cent vingt décibels contre un grand châtaignier
 Cm           G 
D'amour pour toi.

Chorus:
 F           Dm7            Em 
Il est un estuaire un long fleuve de soupirs
          B7                        G 
Ou l'eau mêle nos mystères et nos belles différences
       F              Dm7         Em 
J'y apprendrai a me taire et tes larmes retenir
          B7                          G 
Dans cet autre Finistère aux longues plages de silence.
```

#### Actions
Create a git repo to specify the syntax and put samples for testing.

Write default implementation for java, go and js that generate a default html format providing default css (create a git repo for each implementation).

Create a **syntax highlighter for github !**

So when the format is defined , the rest API may provide by default this format when asking text/plain. The rest API may provide a html view of the song asking the mime type text/html

#### References
Existing syntax:
 - http://www.boiteachansons.net/Txt/Les-Innocents/L-autre-Finistere.txt
 - http://en.wikipedia.org/wiki/Chord_%28software%29

**Comment by jeancharles-roger** [comment]
I kind of like .song, it does match songbook. 

What about songmark for the DSL name ?

**Comment by llgcode** [comment]
agree for this extension and name !

**Comment by jeancharles-roger** [comment]
Nice

**Comment by llgcode** [comment]
Find the spec https://github.com/kawane/songmark/blob/master/Songmark.md here
