### ISSUE TITLE
Display a song in 2 colonnes option

### ISSUE THREAD

**Issue by llgcode** [kawane/songbook#20]
If the song doesn't display entirely on the screen may be try to display it on 2 colonnes

**Comment by jeancharles-roger** [comment]
We should think about a responsive way depending on the media (print, screen, tablet, smartphone).

I think that this functionality is more important than the customization (see #9). The customization shouldn't interfere with layout.

**Comment by llgcode** [comment]
done, but need to make it responsive to remove the button
