### ISSUE TITLE
Using http://undertow.io/ instead of vertx

### ISSUE THREAD

**Issue by llgcode** [kawane/songbook#23]
Vertx is a great framework but it seems that we don't need a framework like this. Vertice and module are too much for our purpose and we don't really understand these abstraction. Undertow is smaller than vertx and has a similar async API, we need to port the code for the [Server](https://github.com/kawane/songbook/blob/master/src/main/java/songbook/server/Server.java) part and [SongDatabase](https://github.com/kawane/songbook/blob/master/src/main/java/songbook/song/SongDatabase.java) part that intensivly use vertx. For this work it's preferable to make a branch cause for now songbook is stable and usable with vertx.

**Comment by jeancharles-roger** [comment]
+1

**Comment by jeancharles-roger** [comment]
There is a working version using undertow in the undertow branch (0dc8df6239164a87bf1e6e77bc722b686e235b7f). Maybe it's time to merge ?

**Comment by llgcode** [comment]
Ok thanks

-- Laurent.

**Comment by jeancharles-roger** [comment]
I've merged it (needed to advance to build the app).

**Comment by llgcode** [comment]
Yes!
 Le 24 avr. 2015 22:21, "Jean-Charles Roger" <notifications@github.com> a
écrit :
