### ISSUE TITLE
The content editable feature isn't sufficient 

### ISSUE THREAD

**Issue by jeancharles-roger** [kawane/songbook#5]
The content editable attribute is great to edit song but it's not sufficient. We need tools to edit chords, tags and others. What is the good level: buttons, keyboard short cuts, conventions, a bit of all, ... ?

What would you propose ?

**Comment by llgcode** [comment]
With the dsl now we can integrate a Text Editor like 
 - http://ace.c9.io/
 - https://codemirror.net/

And provide a Syntax highlighting and maybe completion for metadata and chords

**Comment by jeancharles-roger** [comment]
Maybe a customizable text editor like:

- [http://ckeditor.com/demo#inline] or
- [http://quilljs.com]

Would be more adapted since songs are mostly lyrics.

**Comment by llgcode** [comment]
not sure, now i've adapted an ace mode it seems to do the trick. see this
http://songbook.llgmusic.net/edit/eels-parallels

-- Laurent.

**Comment by jeancharles-roger** [comment]
You're right it works well. The edition is simple !!

Is there a way to hide the text will the editor is loading ?

**Comment by llgcode** [comment]
I don't know maybe using css

-- Laurent.

**Comment by llgcode** [comment]
For now the ace text  ecitor seems to be sufficient
